spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true
application:
  security:
    jwt:
      secret-key: YoVBs+fSApwsrc0fZeUG7tFtyRjc4nIixENeTMlkwSXdmnCSS48XPYhUO29JPqeO
      expiration: 900000
      refresh-token:
        expiration: 604800000
app:
  jwt:
    enabled: true

auth-service:
  base-url: http://AUTH-SERVICE

redis:
  host: 127.0.0.1
  port: 6379