spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/product
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    location: classpath:db.migration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.eCommerce.common.events"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.ecommerce.kafka.OrderConfirmation
        spring.json.trusted.packages: "com.eCommerce.common.events"

server:
  port: 8050
